### PR TITLE
Fix youtube thumbnails

### LINKED ISSUE #262: Youtube video not displaying placeholder image and not playing
At https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2024-05/mesquartierschinois.wordpress.com/

video poster is not displayed (black video) and playing video foes not work

### PR DESCRIPTION
**Pull request by benoit74**
Fix #262 

Changes:
- new fuzzy rule for youtube thumbnails
  - pattern has been slightly enhanced compared to the one suggested in issue to support any file extension

### CODE REVIEW

**Comment by benoit74** [comment]
@mgautierfr I assigned you the review because you are probably more experienced than @rgaudin on these fuzzy rules and I would like you to check if I'm right in what I'm saying on the issue regarding the fact that there is no better way yet to be sure to always use the higher res image present in the WARC / ZIM.

@rgaudin your comments are of course still welcomed ^^

**Comment by benoit74** [comment]
Just rebased the commit so that it is ready to be merged, commit content did not changed.

**Comment by mgautierfr** [comment]
> I assigned you the review because you are probably more experienced than @rgaudin on these fuzzy rules and I would like you to check if I'm right in what I'm saying on the issue regarding the fact that there is no better way yet to be sure to always use the higher res image present in the WARC / ZIM.

I think there is two problems here:
- What the scrapper does (and so what is present in the warc)
- What we do

If the scrapper visits only one thumbnail (and so there is only one thumbnail per video in the warc), it seems we don't have more to do than save the thumbnail using a generic name and always rewrite url to this generic name. This is what the PR does

If the scrapper visits several thumbnails per video, we may want to be smarted on zim file creation. Instead of a "dummy rewrite" looping on all entries and processing each entry at once, we could have advance domain specific rewrite which search the best thumbnail for each video and save only this one (using a generic name here too).

I don't know if we need this advance rewrite (and I don't know how it would integrate in our current architecture neither). But in any case, we would need a generic (and unique per video) name for the thumbnail and this PR is doing that.

So in itself this PR seems good. Advance rewrite (if done) should go in another PR.

**Comment by benoit74** [comment]
Thank you.

As highlighted in the linked issue, the crawler fetches multiple thumbnails per video for some videos (not all, don't know why).

Advanced rewrite is the topic of https://github.com/openzim/warc2zim/issues/271

**Pull request merged**
