### PR TITLE
Url encoding tests

### PR DESCRIPTION
**Pull request by benoit74**
Change:

Add a test case for the URL encoding problems of #206

### CODE REVIEW

**Review by rgaudin — APPROVED** [review]
LGTM

**Comment by rgaudin** [comment]
Oh Codefactor is complaining

**Comment by benoit74** [comment]
I fixed the codefactor complain regarding the test-website. I did nothing for the complex method warning, it is like it is.

**Comment by rgaudin** [comment]
> I fixed the codefactor complain regarding the test-website. I did nothing for the complex method warning, it is like it is.

Good to merge then

**Pull request merged**
