### PR TITLE
Enhance checks regarding availability of `output` folder

### LINKED ISSUE #106: Test output writable is unusable when not successful
I've installed warc2zim on an external hard drive, and everything installs fine using the instructions. 'warc2zim --help' works properly. However, on attempting to use it, I get the following error, shown below. I've retried it several times, and each time the tmp filename changes, obviously, but I'm unsure if this is a bug related to my setup, or if I'm doing something wrong?

warc2zim /input/instructables.warc --output /output --name instructables.zim -u http://www.instructables.com/

Traceback (most recent call last):
  File "/media/alex/deepstorage1/zimittesting/env/bin/warc2zim", line 8, in <module>
    sys.exit(warc2zim())
  File "/media/alex/deepstorage1/zimittesting/env/lib/python3.10/site-packages/warc2zim/main.py", line 818, in warc2zim
    warc2zim = WARC2Zim(r)
  File "/media/alex/deepstorage1/zimittesting/env/lib/python3.10/site-packages/warc2zim/main.py", line 246, in __init__
    with tempfile.NamedTemporaryFile(dir=self.output, delete=True) as fh:
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/output/tmp9479ws_0'

### PR DESCRIPTION
**Pull request by jairajmahadev**
fixes #106

### CODE REVIEW

**Comment by jairajmahadev** [comment]
```logger.debug(f"Attempting to confirm output is writable in directory {self.output}")``` is not being printed in console.
This is what my output looks like:
```
jairajm@LAPTOP-61SES7LN:~/forked/warc2zim$ warc2zim example.warc --output /output --name myarchive.zim 
[ERROR] Failed to write to output directory /output. Make sure output directory exists and is writable. 

Traceback (most recent call last):
  File "/home/jairajm/.pyenv/versions/3.8.19/bin/warc2zim", line 33, in <module>
    sys.exit(load_entry_point('warc2zim==1.5.5', 'console_scripts', 'warc2zim')())
  File "/home/jairajm/.pyenv/versions/3.8.19/lib/python3.8/site-packages/warc2zim-1.5.5-py3.8.egg/warc2zim/main.py", line 112, in main
    converter = Converter(r)
  File "/home/jairajm/.pyenv/versions/3.8.19/lib/python3.8/site-packages/warc2zim-1.5.5-py3.8.egg/warc2zim/converter.py", line 129, in __init__
    with tempfile.NamedTemporaryFile(dir=self.output, delete=True) as fh:
  File "/home/jairajm/.pyenv/versions/3.8.19/lib/python3.8/tempfile.py", line 556, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/jairajm/.pyenv/versions/3.8.19/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/output/tmp95u8_o0h'
```

**Comment by benoit74** [comment]
To activate the output of debug logs you need to pass the `--verbose` CLI flag

**Comment by jairajmahadev** [comment]
Is there a specific exit code I should use?

**Comment by jairajmahadev** [comment]
@benoit74 PR is ready for review.

**Comment by jairajmahadev** [comment]
test output
image

**Comment by jairajmahadev** [comment]
I hope i have squashed the commits correctly. Still learning :)

**Comment by benoit74** [comment]
> I hope i have squashed the commits correctly. Still learning :)

The goal of squashing is to have only one commit with all modifications at once, so that Git history does not trace the history of how we failed to produce proper code at once but trace the history of our intended modifications.

Currently your branch has 5 commits, so it is not squashed at all.

`git rebase -i main` is the way to go ; I suggest to use `r` option on first commit to rewrite the commit message (so that it explains all modifications of this PR) and `f` option on all subsequent commits (to meld them into previous commit). After that, you can `git diff` between your local branch and the remote, and you should see no difference (code is identical, only commit history has changed). If this is true, you can then `git push --force` (force is mandatory when you've rewritten the Git history ; it is not recommended in general but OK when you are working alone on a feature branch - which is the case here).

**Comment by benoit74** [comment]
Btw, I've updated your PR title and suggest to use the same for your Git commit. It is best practice to explain what has been done from the user perspective rather than technical details like try-except

**Comment by jairajmahadev** [comment]
@benoit74 Squashed all commits the way you suggested. Is it correct now?

**Review by benoit74 — CHANGES_REQUESTED** [review]
Oups, CI is failing due to improper formatting.

Please fix (you must call `black` locally)

**Comment by benoit74** [comment]
I had to fix a test which was failing since we are no more raising a regular exception but a system exit.

**Pull request merged**
