### PR TITLE
localization: setup localization using jinja2 and babel (#36)

### PR DESCRIPTION
**Pull request by ikreymer**
- setup localization of all templates (rename replay -> templates)
- add sample localized strings for fr
- run all templates (except sw.js) through jinja
- store string tables in package data
- babel supported via setuptools
- using new 'text/html;raw=true' mime for text/html to avoid rewriting

### CODE REVIEW

**Comment by ikreymer** [comment]
@rgaudin is this what you had in mind for localization? will add brief docs also, using babel with setuptools integration

**Comment by rgaudin** [comment]
@ikreymer yep that's it. Didn't know the babel/setuptools integration, love it! 
I've updated the code to make use of scraperlib ; check latest commit and fixed the french strings.

**Comment by ikreymer** [comment]
Yes, my translations were with google translate :)

Though, some possible issues with the change:
- The default on command line is unset so that it can be detected from html. If it defaults to "eng", then it will not use the HTML detection. (This is why it was `fr` as it was testing extraction from lesfondamentaux page)
- I didn't use zimscraperlib because loading the .mo file from pkg_data, so its not tied to the directory structure. This should allow `warc2zim` to be run from any directory after being installed via pip -- I think zimscraperlib expects the `locale` directory to exist in current working directory.

**Comment by rgaudin** [comment]
>     * The default on command line is unset so that it can be detected from html. If it defaults to "eng", then it will not use the HTML detection. (This is why it was `fr` as it was testing extraction from lesfondamentaux page)

Oh right! My bad. Will change that.

>     * I didn't use zimscraperlib because loading the .mo file from package data using `pkg_resources`, so its not tied to the directory structure. This should allow `warc2zim` to be run from any directory after being installed via pip -- I think zimscraperlib expects the `locale` directory to exist in current working directory.

Nope, you pass it the locale's parent folder and that's it. We're passing it the module folder so it would work anywhere it is installed.

**Comment by ikreymer** [comment]
> 
> Nope, you pass it the locale's parent folder and that's it. We're passing it the module folder so it would work anywhere it is installed.

Ok, i was thinking to make it work with `zip_safe=True, but maybe that's not needed anymore when using pip.
It won't currently work with `python setup.py install` because there's no path, its loading from a .egg but maybe that behavior is obsolete now..

Also, I don't think it should thrown an error when the locale doesn't exist, i think it should just print warning and default to english (with null translations).. eg. if the default HTML pages is some other language

**Comment by rgaudin** [comment]
> Ok, i was thinking to make it work with `zip_safe=True`, but maybe that's not needed anymore when using pip.
> It won't currently work with `python setup.py install` because there's no path, its loading from a .egg but maybe that behavior is obsolete now..

Yes, that's what I meant. made it zip_safe False.

> Also, I don't think it should thrown an error when the locale doesn't exist, i think it should just print warning and default to english (with null translations).. eg. if the default HTML pages is some other language

Agrees, forgot that behavior. Fixed it.

**Pull request merged**
